apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsecurebuckets.yagnesh.cloud
spec:
  group: yagnesh.cloud
  names:
    kind: XSecureBucket
    plural: xsecurebuckets
  claimNames:
    kind: SecureBucket
    plural: securebuckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    type: string
                    description: "AWS Region (e.g. us-east-1)"
                    default: "us-east-1"
                  tags:
                    type: object
                    additionalProperties:
                      type: string
                    description: "Extra tags for the bucket"
                required:
                - region
